default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: contentmaster_development


test:
  <<: *default
  database: contentmaster_test


production:
  primary: &primary_production
    <<: *default
    database: contentmaster_production
    username: contentmaster
    password: <%= ENV["CONTENTMASTER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: contentmaster_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: contentmaster_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: contentmaster_production_cable
    migrations_paths: db/cable_migrate
